server:
  port: 8804
spring:
  application:
    name: eureka-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xxxx/xx
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8801/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh